version: "3.9"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - pilpilangtestdb:/var/lib/postgresql/data
volumes:
  pilpilangtestdb: {}
