/* CREATE POLICY thing ON messages m1
    FOR INSERT WITH CHECK
        (EXISTS (
            SELECT * FROM
                users u1
            WHERE
                u1.id = current_user
            AND
                u1.alcohol_ppm < 5
            ));
 */
-- Plan B:

CREATE TABLE users (
    id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username   varchar(40),
    alcohol_ppm integer
);

CREATE TABLE chats (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user1_id integer references users(id),
    user2_id integer references users(id)
);

CREATE TABLE messages (
    content TEXT,
    chat_id integer references chats(id)
);

CREATE POLICY thing_policy ON messages FOR INSERT WITH CHECK (
    5 -- current user
    IN (
        SELECT u.id FROM users u, chats mchat
        WHERE messages.chat_id = mchat.id
        AND NOT u.id IN
            (SELECT p.id FROM users p WHERE p.alcohol_ppm < 5)
        AND ROW(mchat.id, u.id) IN
            (SELECT u.id, c.id FROM chats c, users u
                WHERE u.id = c.user1_id
                   OR u.id = c.user2_id)
    )
);

